# Generated by Django 3.1.1 on 2020-09-27 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20200921_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 16, 17, 51, 149939)),
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
