# Generated by Django 3.1.1 on 2020-09-27 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20200927_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 16, 22, 53, 486596)),
        ),
    ]
