# Generated by Django 3.1.1 on 2020-09-27 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20200927_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 16, 35, 27, 354054)),
        ),
    ]
