# Generated by Django 3.1.1 on 2020-10-27 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20200927_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 10, 17, 10, 897201)),
        ),
    ]
